{
  # catch does nothing.
  catch: m{|errType, f| self},
}
